# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    # do we still need these 3 lines?
    annotations:
        enabled: false
    http_method_override: false
    handle_all_throwables: true


    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
#    session: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true

    http_client:
        default_options:
            headers:
                'User-Agent': 'Survos (tacman@gmail.com)'
            max_redirects: 3
            proxy: '%env(HTTP_PROXY)%'

    router:
        default_uri: '%env(BASE_URL)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
