# config/packages/liip_imagine.yamn
# liip_imagine:
#     driver: gd
#     twig:
#         mode: lazy
liip_imagine:
  resolvers:
    default:
      web_path: ~

  loaders:
    default:
      filesystem:
        data_root:
          - '%kernel.project_dir%/public'
          - '%kernel.project_dir%/../../shared/public'


    # default loader to use for all filter sets
    data_loader: flysystem_loader

    filter_sets:
        auto_rotate: ~
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [400, 400]
                    allow_upscale: true
                    mode: inset
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [200, 200]
                    allow_upscale: true
                    mode: inset

        squared_thumbnail_tiny:
            filters:
                thumbnail:
                    size:          [100, 100]
                    allow_upscale: true
                    mode: inset

