# .symfony.local.yaml
workers:
  # built-in command that builds and watches front-end assets

#   built-in command that starts messenger consumer
  messenger_consume_meili:
       cmd: ['symfony', 'console', 'messenger:consume', 'meili']
       watch: ['config', 'src', 'templates', 'vendor']
#  messenger_consume_congress:
#      cmd: ['symfony', 'console', 'messenger:consume', 'meili']
#      watch: ['config', 'src', 'templates', 'vendor']

#  messenger_consume_async: ~

  # you can also add your own custom commands
#  build_spa:
#    cmd: ['yarn', '--cwd', './spa/', 'dev']

