<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\MarvelRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity using data from data/marvel.jsonl
 */
#[Entity(repositoryClass: MarvelRepository::class)]
#[MeiliIndex(filterable: ['powers','species','teams','authors'], sortable: [], searchable: ['name','description'])]
final class Marvel
{
	#[Column(length: 255, nullable: true)]
	#[Id]
	public ?string $code = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $aliases = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $authors = null;

	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $description = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $images = null;

	#[Column(length: 255, nullable: true)]
	public ?string $mainColor = null;

	#[Column(length: 255, nullable: true)]
	public ?string $name = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $partners = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $powers = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $ranking = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $secretIdentities = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $species = null;

	#[Column(length: 255, nullable: true)]
	public ?string $superName = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $teams = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $urls = null;
}
