<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\MarvelRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity
 * @source data/marvel.jsonl
 */
#[Entity(repositoryClass: MarvelRepository::class)]
#[MeiliIndex(
	primaryKey: 'code',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Marvel
{
	public const FILTERABLE_FIELDS = [
		'authors',
		'powers',
		'teams',
		'species',
		'partners',
	];

	public const SORTABLE_FIELDS = [];
	public const SEARCHABLE_FIELDS = ['description'];

	/**
	 * Field: aliases
	 * total=1786, nulls=0, distinct=501 (capped)
	 * Top/First value: ["8-Ball","Eightball","The Crook With the Jet-Propelled Cue-Stick"]
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $aliases = null;

	/**
	 * Field: authors
	 * total=1743, nulls=0, distinct=501 (capped)
	 * Top/First value: ["Bob Budiansky","Bret Blevins"]
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $authors = null;

	/**
	 * Field: description
	 * total=1719, nulls=0, distinct=501 (capped)
	 * length: 3–532 chars
	 * Top/First value: "8-Ball is the name used by different characters from Marvel Comics."
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $description = null;

	/**
	 * Field: images
	 * total=1298, nulls=0, distinct=501 (capped)
	 * Top/First value: {"thumbnail":"https:\/\/upload.wikimedia.org\/wikipedia\/en\/thumb\/0\/09\/8-Ball_%28comics%29_sleepwalker_cover.jpg\/250px-8-Ball_%28comics%29_sleepwalker_cover.jpg"}
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $images = null;

	/**
	 * Field: name
	 * total=1809, nulls=0, distinct=501 (capped)
	 * length: 1–47 chars
	 * Top/First value: "8-Ball"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 47, nullable: true)]
	public ?string $name = null;

	/**
	 * Field: powers
	 * total=1518, nulls=0, distinct=501 (capped)
	 * Top/First value: ["A cue stick","Brilliant engineer","Expert pool player","Fireworks","Flying miniature cameras","Gifted inventor","Skilled gymnast","Use of explosive grenades"]
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $powers = null;

	/**
	 * Field: ranking
	 * total=1809, nulls=0, distinct=501 (capped)
	 * Top/First value: {"comicCount":0,"eventCount":0,"pageviewCount":689,"serieCount":0,"storyCount":0}
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $ranking = null;

	/**
	 * Field: secret_identities
	 * total=1471, nulls=0, distinct=501 (capped)
	 * Top/First value: ["Jeff Hagees"]
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $secretIdentities = null;

	/**
	 * Field: super_name
	 * total=1809, nulls=0, distinct=501 (capped)
	 * length: 1–28 chars
	 * Top/First value: "8-Ball"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 28, nullable: true)]
	public ?string $superName = null;

	/**
	 * Field: teams
	 * total=1479, nulls=0, distinct=501 (capped)
	 * Top/First value: ["8-Ball Gang"]
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $teams = null;

	/**
	 * Field: urls
	 * total=1809, nulls=0, distinct=501 (capped)
	 * Top/First value: {"wikipedia":"https:\/\/en.wikipedia.org\/wiki\/8-Ball_(comics)"}
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $urls = null;

	/**
	 * Field: code
	 * total=1809, nulls=0, distinct=501 (capped)
	 * length: 1–44 chars
	 * Top/First value: "8-Ball"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 44, nullable: true)]
	#[Id]
	public ?string $code = null;

	/**
	 * Field: species
	 * total=734, nulls=0, distinct=141
	 * Top/First value: ["Human"]
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $species = null;

	/**
	 * Field: partners
	 * total=248, nulls=0, distinct=228
	 * Top/First value: ["Beast"]
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $partners = null;

	/**
	 * Field: main_color
	 * total=70, nulls=0, distinct=7
	 * Top/First value: {"blue":9,"green":36,"hexa":"3A2409","red":58}
	 */
	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $mainColor = null;
}
