<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\WcmaRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity using data from data/wcma.csv
 */
#[Entity(repositoryClass: WcmaRepository::class)]
#[MeiliIndex(primaryKey: null, filterable: [
    'classification',
    'period',
], sortable: [], searchable: [
    'title',
    'description',
    'objectName',
    'inscription'
])]
final class Wcma
{
	#[Column(type: Types::INTEGER, nullable: true)]
	#[Id]
	public ?int $id = null;

	#[Column(length: 255, nullable: true)]
	public ?string $accessionNumber = null;

	#[Column(length: 255, nullable: true)]
	public ?string $title = null;

	#[Column(length: 255, nullable: true)]
	public ?string $maker = null;

	#[Column(length: 255, nullable: true)]
	public ?string $department = null;

	#[Column(length: 255, nullable: true)]
	public ?string $classification = null;

	#[Column(length: 255, nullable: true)]
	public ?string $culture = null;

	#[Column(length: 255, nullable: true)]
	public ?string $period = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $creationDate = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $creationDateEarliest = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $creationDateLatest = null;

	#[Column(length: 255, nullable: true)]
	public ?string $sourceName = null;

	#[Column(length: 255, nullable: true)]
	public ?string $objectName = null;

	#[Column(length: 255, nullable: true)]
	public ?string $medium = null;

	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $description = null;

	#[Column(length: 255, nullable: true)]
	public ?string $creditLine = null;

	#[Column(length: 255, nullable: true)]
	public ?string $paperSupport = null;

	#[Column(length: 255, nullable: true)]
	public ?string $catalogueRaisonne = null;

	#[Column(length: 255, nullable: true)]
	public ?string $portfolio = null;

	#[Column(length: 255, nullable: true)]
	public ?string $signed = null;

	#[Column(length: 255, nullable: true)]
	public ?string $marks = null;

	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $inscription = null;

	#[Column(length: 255, nullable: true)]
	public ?string $filename = null;

	#[Column(length: 255, nullable: true)]
	public ?string $dimensions = null;

	#[Column(length: 255, nullable: true)]
	public ?string $elementType = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $widthCm = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $heightCm = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $depthCm = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $widthIn = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $heightIn = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $depthIn = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $areaIn = null;

	#[Column(length: 255, nullable: true)]
	public ?string $sizeSML = null;

	#[Column(length: 255, nullable: true)]
	public ?string $is3d = null;

	#[Column(length: 255, nullable: true)]
	public ?string $orientationPLS = null;

	#[Column(length: 255, nullable: true)]
	public ?string $accessionDate = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ULAN = null;

	#[Column(length: 255, nullable: true)]
	public ?string $copyrightHolder = null;

	#[Column(length: 255, nullable: true)]
	public ?string $dataDate = null;

	#[Column(length: 255, nullable: true)]
	public ?string $academicUse = null;
}
