<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\WineRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;

/**
 * @generated by code:entity using data from data/wine.json
 */
#[Entity(repositoryClass: WineRepository::class)]
final class Wine
{
	#[Column(length: 255, nullable: true)]
	#[Id]
	public ?string $name = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $year = null;

	#[Column(length: 255, nullable: true)]
	public ?string $type = null;

	#[Column(length: 255, nullable: true)]
	public ?string $domain = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $quantity = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $price = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $quality = null;

	#[Column(length: 255, nullable: true)]
	public ?string $image = null;
}
