<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\WineRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity
 * @source data/wine.jsonl
 */
#[Entity(repositoryClass: WineRepository::class)]
#[MeiliIndex(
	primaryKey: 'code',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Wine
{
	public const FILTERABLE_FIELDS = ['year', 'type', 'domain', 'quantity', 'price', 'quality'];
	public const SORTABLE_FIELDS = ['year', 'quantity', 'price', 'quality'];
	public const SEARCHABLE_FIELDS = [];

	/**
	 * Field: name
	 * total=1024, nulls=0, distinct=81
	 * length: 7–50 chars
	 * Top/First value: "Chateau Cote Montpezat Castillon Cuvee Compostelle"
	 */
	#[Column(length: 50, nullable: true)]
	public ?string $name = null;

	/**
	 * Field: year
	 * total=1024, nulls=0, distinct=14
	 * Top/First value: 2010
	 * Facet candidate
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $year = null;

	/**
	 * Field: type
	 * total=1024, nulls=0, distinct=2
	 * length: 3–5 chars
	 * Top/First value: "red"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(length: 5, nullable: true)]
	public ?string $type = null;

	/**
	 * Field: domain
	 * total=1024, nulls=0, distinct=13
	 * length: 5–27 chars
	 * Top/First value: "Saint-Emilion"
	 * Facet candidate
	 */
	#[Column(length: 27, nullable: true)]
	public ?string $domain = null;

	/**
	 * Field: quantity
	 * total=1024, nulls=0, distinct=1
	 * Top/First value: 750
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $quantity = null;

	/**
	 * Field: price
	 * total=1024, nulls=0, distinct=52
	 * Top/First value: 26
	 * Facet candidate
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $price = null;

	/**
	 * Field: quality
	 * total=1024, nulls=0, distinct=14
	 * Top/First value: 90
	 * Facet candidate
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $quality = null;

	/**
	 * Field: image
	 * total=1024, nulls=0, distinct=501 (capped)
	 * length: 32–82 chars
	 * Top/First value: "wine/Chateau-Cote-Montpezat-Castillon-Cuvee-Compostelle-2010-Saint-Emilion-0.jpg"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 82, nullable: true)]
	public ?string $image = null;

	/**
	 * Field: code
	 * total=1024, nulls=0, distinct=501 (capped)
	 * length: 23–73 chars
	 * Top/First value: "Chateau-Cote-Montpezat-Castillon-Cuvee-Compostelle-2010-Saint-Emilion-0"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 73, nullable: true)]
	#[Id]
	public ?string $code = null;
}
