<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\WmcaRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;

/**
 * @generated by code:entity
 * @source data/wcma.jsonl
 */
#[Entity(repositoryClass: WmcaRepository::class)]
final class Wmca
{
	/**
	 * Field: id
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * Top/First value: 1
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	#[Id]
	public ?int $id = null;

	/**
	 * Field: accession_number
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 4–17 chars
	 * Top/First value: "39.1.400"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 17, nullable: true)]
	public ?string $accessionNumber = null;

	/**
	 * Field: title
	 * total=17092, nulls=0, distinct=1025 (capped)
	 * length: 1–327 chars
	 * Top/First value: "GRANDE MATINÉE DE BIENFAISANCE EN L'HONNEUR DES POILUS DES RÉGIONS ENVAHIES"
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $title = null;

	/**
	 * Field: maker
	 * total=17086, nulls=0, distinct=1025 (capped)
	 * length: 3–104 chars
	 * Top/First value: "Adrien Barrère"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 104, nullable: true)]
	public ?string $maker = null;

	/**
	 * Field: department
	 * total=17093, nulls=0, distinct=1
	 * length: 4 chars
	 * Top/First value: "WCMA"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $department = null;

	/**
	 * Field: classification
	 * total=17093, nulls=0, distinct=16
	 * length: 10–23 chars
	 * Top/First value: "WCMA-PRINTS"
	 * Facet candidate
	 */
	#[Column(length: 23, nullable: true)]
	public ?string $classification = null;

	/**
	 * Field: creation_date
	 * total=16970, nulls=0, distinct=1025 (capped)
	 * length: 4–81 chars
	 * Top/First value: "1917"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 81, nullable: true)]
	public ?string $creationDate = null;

	/**
	 * Field: creation_date_earliest
	 * total=17093, nulls=0, distinct=575
	 * length: 1–5 chars
	 * Top/First value: "1917"
	 */
	#[Column(length: 5, nullable: true)]
	public ?string $creationDateEarliest = null;

	/**
	 * Field: creation_date_latest
	 * total=17093, nulls=0, distinct=556
	 * length: 1–5 chars
	 * Top/First value: "1917"
	 */
	#[Column(length: 5, nullable: true)]
	public ?string $creationDateLatest = null;

	/**
	 * Field: source_name
	 * total=17093, nulls=0, distinct=1
	 * length: 30 chars
	 * Top/First value: "Williams College Museum of Art"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $sourceName = null;

	/**
	 * Field: object_name
	 * total=17092, nulls=0, distinct=474
	 * length: 3–42 chars
	 * Top/First value: "poster"
	 */
	#[Column(length: 42, nullable: true)]
	public ?string $objectName = null;

	/**
	 * Field: medium
	 * total=16957, nulls=0, distinct=1025 (capped)
	 * length: 2–200 chars
	 * Top/First value: "poster"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 200, nullable: true)]
	public ?string $medium = null;

	/**
	 * Field: credit_line
	 * total=17051, nulls=0, distinct=1025 (capped)
	 * length: 12–288 chars
	 * Top/First value: "Anonymous gift"
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $creditLine = null;

	/**
	 * Field: width_cm
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 3–7 chars
	 * Top/First value: "0.0"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 7, nullable: true)]
	public ?string $widthCm = null;

	/**
	 * Field: height_cm
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 3–7 chars
	 * Top/First value: "0.0"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 7, nullable: true)]
	public ?string $heightCm = null;

	/**
	 * Field: depth_cm
	 * total=17093, nulls=0, distinct=350
	 * length: 3–6 chars
	 * Top/First value: "0.0"
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $depthCm = null;

	/**
	 * Field: width_in
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 3–6 chars
	 * Top/First value: "0.0"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $widthIn = null;

	/**
	 * Field: height_in
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 3–7 chars
	 * Top/First value: "0.0"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 7, nullable: true)]
	public ?string $heightIn = null;

	/**
	 * Field: depth_in
	 * total=17093, nulls=0, distinct=334
	 * length: 3–6 chars
	 * Top/First value: "0.0"
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $depthIn = null;

	/**
	 * Field: area_in
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 3–9 chars
	 * Top/First value: "0.0"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 9, nullable: true)]
	public ?string $areaIn = null;

	/**
	 * Field: accession_date
	 * total=16429, nulls=0, distinct=448
	 * length: 4–10 chars
	 * Top/First value: "1939-01-01"
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $accessionDate = null;

	/**
	 * Field: ULAN
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 5–20 chars
	 * Top/First value: " 500103823"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 20, nullable: true)]
	public ?string $ULAN = null;

	/**
	 * Field: data_date
	 * total=17093, nulls=0, distinct=1
	 * length: 16 chars
	 * Top/First value: "2023-12-14 08:01"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $dataDate = null;

	/**
	 * Field: citation_url
	 * total=17093, nulls=0, distinct=1025 (capped)
	 * length: 39–43 chars
	 * Top/First value: "https://egallery.williams.edu/objects/1"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 43, nullable: true)]
	public ?string $citationUrl = null;

	/**
	 * Field: inscription
	 * total=10233, nulls=0, distinct=1025 (capped)
	 * length: 4–1787 chars
	 * Top/First value: "l.r. in pencil: BNauman 8/20 75"
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $inscription = null;

	/**
	 * Field: dimensions
	 * total=16384, nulls=0, distinct=1025 (capped)
	 * length: 4–254 chars
	 * Top/First value: "sheet: 30 1/8 x 83 7/16 in. (76.5 x 212 cm)"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 254, nullable: true)]
	public ?string $dimensions = null;

	/**
	 * Field: element_type
	 * total=15089, nulls=0, distinct=3
	 * length: 5–7 chars
	 * Top/First value: "sheet"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $elementType = null;

	/**
	 * Field: size_s_m_l
	 * total=15089, nulls=0, distinct=3
	 * length: 5–6 chars
	 * Top/First value: "large"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $sizeSML = null;

	/**
	 * Field: is_3d
	 * total=17092, nulls=0, distinct=2
	 * length: 4–5 chars
	 * Top/First value: "false"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $is3d = null;

	/**
	 * Field: orientation_p_l_s
	 * total=14825, nulls=0, distinct=3
	 * length: 1 chars
	 * Top/First value: "L"
	 * Facet candidate
	 * Boolean-like
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $orientationPLS = null;

	/**
	 * Field: copyright_holder
	 * total=5292, nulls=0, distinct=185
	 * length: 9–141 chars
	 * Top/First value: "Artists Rights Society (ARS)"
	 */
	#[Column(length: 141, nullable: true)]
	public ?string $copyrightHolder = null;

	/**
	 * Field: description
	 * total=3457, nulls=0, distinct=1025 (capped)
	 * length: 1–1297 chars
	 * Top/First value: "green ground; dark green backing; striped brocaded gros de Tours-style silk with embroidery"
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $description = null;

	/**
	 * Field: culture
	 * total=1514, nulls=0, distinct=198
	 * length: 1–51 chars
	 * Top/First value: "Japanese"
	 */
	#[Column(length: 51, nullable: true)]
	public ?string $culture = null;

	/**
	 * Field: academic_use
	 * total=2895, nulls=0, distinct=1025 (capped)
	 * length: 4–582 chars
	 * Top/First value: "|ARTS 253"
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $academicUse = null;

	/**
	 * Field: paper_support
	 * total=134, nulls=0, distinct=100
	 * length: 5–218 chars
	 * Top/First value: "polyester film base"
	 */
	#[Column(length: 218, nullable: true)]
	public ?string $paperSupport = null;

	/**
	 * Field: catalogue_raisonne
	 * total=1112, nulls=0, distinct=988
	 * length: 4–218 chars
	 * Top/First value: "Kennedy 66, III/III; Glasgow 70 6/6"
	 */
	#[Column(length: 218, nullable: true)]
	public ?string $catalogueRaisonne = null;

	/**
	 * Field: portfolio
	 * total=522, nulls=0, distinct=87
	 * length: 3–68 chars
	 * Top/First value: "A Series of Sixteen Etchings of Scenes on the Thames; The Thames Set"
	 */
	#[Column(length: 68, nullable: true)]
	public ?string $portfolio = null;

	/**
	 * Field: signed
	 * total=163, nulls=0, distinct=102
	 * length: 2–256 chars
	 * Top/First value: "Entitled and signed, "Lan Ying," and with two seals of the artist."
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $signed = null;

	/**
	 * Field: filename
	 * total=16413, nulls=0, distinct=1025 (capped)
	 * length: 7–66 chars
	 * Top/First value: "IMG_92.18.H.jpg"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 66, nullable: true)]
	public ?string $filename = null;

	/**
	 * Field: period
	 * total=150, nulls=0, distinct=34
	 * length: 4–28 chars
	 * Top/First value: "Hellenistic"
	 * Facet candidate
	 */
	#[Column(length: 28, nullable: true)]
	public ?string $period = null;

	/**
	 * Field: marks
	 * total=178, nulls=0, distinct=176
	 * length: 11–254 chars
	 * Top/First value: "Some pencil marks and stamp on verso"
	 */
	#[Column(length: 254, nullable: true)]
	public ?string $marks = null;
}
