survos_command:
#  prefix: /admin/commands
  type: attribute
#  resource:
#    path: '@SurvosCommandBundle/src/Controller/'
#    namespace: Survos\CommandBundle\Controller

  resource: '@SurvosCommandBundle/config/routes.yaml'

when@dev:
  survos_command:
    resource: '@SurvosCommandBundle/config/routes.yaml'
#    prefix: '/command'

