<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251125214354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE car (dimensions_height VARCHAR(3) DEFAULT NULL, dimensions_length VARCHAR(3) DEFAULT NULL, dimensions_width VARCHAR(3) DEFAULT NULL, engine_information_driveline VARCHAR(17) DEFAULT NULL, engine_information_engine_type VARCHAR(60) DEFAULT NULL, engine_information_hybrid VARCHAR(4) DEFAULT NULL, engine_information_number_of_forward_gears VARCHAR(1) DEFAULT NULL, engine_information_transmission VARCHAR(30) DEFAULT NULL, fuel_information_city_mpg VARCHAR(2) DEFAULT NULL, fuel_information_fuel_type VARCHAR(22) DEFAULT NULL, fuel_information_highway_mpg VARCHAR(3) DEFAULT NULL, identification_classification VARCHAR(22) DEFAULT NULL, identification_id VARCHAR(67) DEFAULT NULL, identification_make VARCHAR(18) DEFAULT NULL, identification_model_year VARCHAR(48) DEFAULT NULL, identification_year VARCHAR(4) DEFAULT NULL, engine_information_engine_statistics_horsepower VARCHAR(3) DEFAULT NULL, engine_information_engine_statistics_torque VARCHAR(3) DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE image (original_url TEXT NOT NULL, code TEXT NOT NULL, resized JSON DEFAULT NULL, original_size INT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, product_id VARCHAR(255) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE INDEX IDX_C53D045F4584665A ON image (product_id)');
        $this->addSql('CREATE TABLE instrument (name TEXT NOT NULL, description TEXT NOT NULL, type VARCHAR(255) DEFAULT NULL, tags JSONB DEFAULT NULL, genres JSONB DEFAULT NULL, countries JSONB DEFAULT NULL, id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE jeopardy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question TEXT NOT NULL, category VARCHAR(255) NOT NULL, air_date DATE NOT NULL, answer VARCHAR(255) NOT NULL, value INT DEFAULT NULL, round VARCHAR(255) NOT NULL, comments TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE marvel (aliases JSONB DEFAULT NULL, authors JSONB DEFAULT NULL, description TEXT DEFAULT NULL, images JSONB DEFAULT NULL, name VARCHAR(47) DEFAULT NULL, powers JSONB DEFAULT NULL, ranking JSONB DEFAULT NULL, secret_identities JSONB DEFAULT NULL, species JSONB DEFAULT NULL, super_name VARCHAR(28) DEFAULT NULL, teams JSONB DEFAULT NULL, urls JSONB DEFAULT NULL, code VARCHAR(44) NOT NULL, partners JSONB DEFAULT NULL, main_color JSONB DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE messenger_processed_messages (run_id INT NOT NULL, attempt SMALLINT NOT NULL, message_type VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, dispatched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wait_time BIGINT NOT NULL, handle_time BIGINT NOT NULL, memory_usage INT NOT NULL, transport VARCHAR(255) NOT NULL, tags VARCHAR(255) DEFAULT NULL, failure_type VARCHAR(255) DEFAULT NULL, failure_message TEXT DEFAULT NULL, results JSON DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title TEXT NOT NULL, genre JSON NOT NULL, year INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE official (id VARCHAR(255) NOT NULL, first_name VARCHAR(16) DEFAULT NULL, last_name VARCHAR(32) NOT NULL, official_name VARCHAR(48) NOT NULL, birthday DATE DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, current_party VARCHAR(12) DEFAULT NULL, code VARCHAR(255) NOT NULL, house VARCHAR(255) DEFAULT NULL, state VARCHAR(2) DEFAULT NULL, district INT DEFAULT NULL, wikidata_id VARCHAR(255) DEFAULT NULL, wiki_data JSONB DEFAULT NULL, image_codes JSONB DEFAULT NULL, image_count INT DEFAULT NULL, ids JSON DEFAULT NULL, original_image_url VARCHAR(255) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE product (sku VARCHAR(255) NOT NULL, data JSONB DEFAULT NULL, category VARCHAR(255) DEFAULT NULL, brand VARCHAR(255) DEFAULT NULL, rating INT NOT NULL, stock INT NOT NULL, tags JSONB DEFAULT NULL, title_backing TEXT DEFAULT NULL, description_backing TEXT DEFAULT NULL, PRIMARY KEY (sku))');
        $this->addSql('CREATE TABLE term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(16) DEFAULT NULL, state_abbreviation VARCHAR(2) DEFAULT NULL, party VARCHAR(12) DEFAULT NULL, district VARCHAR(8) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, official_id VARCHAR NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A50FE78D4D88E615 ON term (official_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE wam (title VARCHAR(10) NOT NULL, url VARCHAR(60) DEFAULT NULL, wam_image VARCHAR(135) DEFAULT NULL, collection VARCHAR(16) DEFAULT NULL, description TEXT DEFAULT NULL, keywords TEXT DEFAULT NULL, registration_number VARCHAR(10) DEFAULT NULL, subject VARCHAR(89) DEFAULT NULL, thumbnail VARCHAR(123) DEFAULT NULL, accession_number VARCHAR(20) DEFAULT NULL, cataloguer VARCHAR(50) DEFAULT NULL, condition VARCHAR(56) DEFAULT NULL, creator VARCHAR(25) DEFAULT NULL, medium VARCHAR(11) DEFAULT NULL, medium_format VARCHAR(28) DEFAULT NULL, original_legal_broker VARCHAR(50) DEFAULT NULL, state VARCHAR(6) DEFAULT NULL, notes TEXT DEFAULT NULL, notes2 TEXT DEFAULT NULL, location VARCHAR(36) DEFAULT NULL, digital_id VARCHAR(10) DEFAULT NULL, PRIMARY KEY (title))');
        $this->addSql('CREATE TABLE wcma (id INT NOT NULL, accession_number VARCHAR(17) DEFAULT NULL, title TEXT DEFAULT NULL, maker VARCHAR(105) DEFAULT NULL, department VARCHAR(4) DEFAULT NULL, classification VARCHAR(23) DEFAULT NULL, creation_date VARCHAR(81) DEFAULT NULL, creation_date_earliest VARCHAR(5) DEFAULT NULL, creation_date_latest VARCHAR(5) DEFAULT NULL, source_name VARCHAR(30) DEFAULT NULL, object_name VARCHAR(42) DEFAULT NULL, medium VARCHAR(200) DEFAULT NULL, credit_line TEXT DEFAULT NULL, width_cm VARCHAR(7) DEFAULT NULL, height_cm VARCHAR(7) DEFAULT NULL, depth_cm VARCHAR(6) DEFAULT NULL, width_in VARCHAR(6) DEFAULT NULL, height_in VARCHAR(7) DEFAULT NULL, depth_in VARCHAR(6) DEFAULT NULL, area_in VARCHAR(9) DEFAULT NULL, accession_date VARCHAR(10) DEFAULT NULL, ulan VARCHAR(20) DEFAULT NULL, data_date VARCHAR(16) DEFAULT NULL, citation_url VARCHAR(43) DEFAULT NULL, manifest VARCHAR(80) DEFAULT NULL, inscription TEXT DEFAULT NULL, text VARCHAR(255) DEFAULT NULL, element_type VARCHAR(7) DEFAULT NULL, size_sml VARCHAR(6) DEFAULT NULL, is3d VARCHAR(5) DEFAULT NULL, orientation_pls VARCHAR(1) DEFAULT NULL, copyright_holder VARCHAR(141) DEFAULT NULL, description TEXT DEFAULT NULL, culture VARCHAR(51) DEFAULT NULL, academic_use TEXT DEFAULT NULL, paper_support VARCHAR(218) DEFAULT NULL, catalogue_raisonne VARCHAR(218) DEFAULT NULL, portfolio VARCHAR(68) DEFAULT NULL, signed TEXT DEFAULT NULL, filename VARCHAR(66) DEFAULT NULL, period VARCHAR(28) DEFAULT NULL, marks VARCHAR(254) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE wine (name VARCHAR(50) DEFAULT NULL, year INT DEFAULT NULL, type VARCHAR(5) DEFAULT NULL, domain VARCHAR(27) DEFAULT NULL, quantity INT DEFAULT NULL, price INT DEFAULT NULL, quality INT DEFAULT NULL, image VARCHAR(83) DEFAULT NULL, code VARCHAR(73) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE wmca (id INT NOT NULL, accession_number VARCHAR(17) DEFAULT NULL, title TEXT DEFAULT NULL, maker VARCHAR(104) DEFAULT NULL, department BOOLEAN DEFAULT NULL, classification VARCHAR(23) DEFAULT NULL, creation_date VARCHAR(81) DEFAULT NULL, creation_date_earliest VARCHAR(5) DEFAULT NULL, creation_date_latest VARCHAR(5) DEFAULT NULL, source_name BOOLEAN DEFAULT NULL, object_name VARCHAR(42) DEFAULT NULL, medium VARCHAR(200) DEFAULT NULL, credit_line TEXT DEFAULT NULL, width_cm VARCHAR(7) DEFAULT NULL, height_cm VARCHAR(7) DEFAULT NULL, depth_cm VARCHAR(6) DEFAULT NULL, width_in VARCHAR(6) DEFAULT NULL, height_in VARCHAR(7) DEFAULT NULL, depth_in VARCHAR(6) DEFAULT NULL, area_in VARCHAR(9) DEFAULT NULL, accession_date VARCHAR(10) DEFAULT NULL, ulan VARCHAR(20) DEFAULT NULL, data_date BOOLEAN DEFAULT NULL, citation_url VARCHAR(43) DEFAULT NULL, inscription TEXT DEFAULT NULL, dimensions VARCHAR(254) DEFAULT NULL, element_type BOOLEAN DEFAULT NULL, size_sml BOOLEAN DEFAULT NULL, is3d BOOLEAN DEFAULT NULL, orientation_pls BOOLEAN DEFAULT NULL, copyright_holder VARCHAR(141) DEFAULT NULL, description TEXT DEFAULT NULL, culture VARCHAR(51) DEFAULT NULL, academic_use TEXT DEFAULT NULL, paper_support VARCHAR(218) DEFAULT NULL, catalogue_raisonne VARCHAR(218) DEFAULT NULL, portfolio VARCHAR(68) DEFAULT NULL, signed TEXT DEFAULT NULL, filename VARCHAR(66) DEFAULT NULL, period VARCHAR(28) DEFAULT NULL, marks VARCHAR(254) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE work (id UUID NOT NULL, title TEXT NOT NULL, type VARCHAR(255) DEFAULT NULL, tags JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F4584665A FOREIGN KEY (product_id) REFERENCES product (sku) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE term ADD CONSTRAINT FK_A50FE78D4D88E615 FOREIGN KEY (official_id) REFERENCES official (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F4584665A');
        $this->addSql('ALTER TABLE term DROP CONSTRAINT FK_A50FE78D4D88E615');
        $this->addSql('DROP TABLE car');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE instrument');
        $this->addSql('DROP TABLE jeopardy');
        $this->addSql('DROP TABLE marvel');
        $this->addSql('DROP TABLE messenger_processed_messages');
        $this->addSql('DROP TABLE movie');
        $this->addSql('DROP TABLE official');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE term');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE wam');
        $this->addSql('DROP TABLE wcma');
        $this->addSql('DROP TABLE wine');
        $this->addSql('DROP TABLE wmca');
        $this->addSql('DROP TABLE work');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
