<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250626110525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE official (id VARCHAR(255) NOT NULL, first_name VARCHAR(16) DEFAULT NULL, last_name VARCHAR(32) NOT NULL, official_name VARCHAR(48) NOT NULL, birthday DATE DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, current_party VARCHAR(12) DEFAULT NULL, code VARCHAR(255) NOT NULL, house VARCHAR(255) DEFAULT NULL, state VARCHAR(2) DEFAULT NULL, district INT DEFAULT NULL, wikidata_id VARCHAR(255) DEFAULT NULL, wiki_data JSONB DEFAULT NULL, image_codes JSONB DEFAULT NULL, image_count INT DEFAULT NULL, ids JSON DEFAULT NULL, original_image_url VARCHAR(255) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(16) DEFAULT NULL, state_abbreviation VARCHAR(2) DEFAULT NULL, party VARCHAR(12) DEFAULT NULL, district VARCHAR(8) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, official_id VARCHAR NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A50FE78D4D88E615 ON term (official_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE term ADD CONSTRAINT FK_A50FE78D4D88E615 FOREIGN KEY (official_id) REFERENCES official (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE term DROP CONSTRAINT FK_A50FE78D4D88E615
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE official
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE term
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE messenger_messages
        SQL);
    }
}
