<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126095701 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE movie ADD overview TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD tags JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD genres JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD director VARCHAR(34) DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD actors JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD characters JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD votes INT DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD rating VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD popularity VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD budget INT DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD poster_url VARCHAR(63) DEFAULT NULL');
        $this->addSql('ALTER TABLE movie DROP genre');
        $this->addSql('ALTER TABLE movie ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE movie ALTER title TYPE VARCHAR(94)');
        $this->addSql('ALTER TABLE movie ALTER title DROP NOT NULL');
        $this->addSql('ALTER TABLE movie ALTER year DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE movie ADD genre JSON NOT NULL');
        $this->addSql('ALTER TABLE movie DROP overview');
        $this->addSql('ALTER TABLE movie DROP tags');
        $this->addSql('ALTER TABLE movie DROP genres');
        $this->addSql('ALTER TABLE movie DROP director');
        $this->addSql('ALTER TABLE movie DROP actors');
        $this->addSql('ALTER TABLE movie DROP characters');
        $this->addSql('ALTER TABLE movie DROP votes');
        $this->addSql('ALTER TABLE movie DROP rating');
        $this->addSql('ALTER TABLE movie DROP popularity');
        $this->addSql('ALTER TABLE movie DROP budget');
        $this->addSql('ALTER TABLE movie DROP poster_url');
        $this->addSql('ALTER TABLE movie ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE movie ALTER title TYPE TEXT');
        $this->addSql('ALTER TABLE movie ALTER title SET NOT NULL');
        $this->addSql('ALTER TABLE movie ALTER year SET NOT NULL');
    }
}
