<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250129132815 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE processed_messages_id_seq CASCADE');
        $this->addSql('DROP TABLE processed_messages');
        $this->addSql('ALTER TABLE official ADD ids JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE official ADD marking VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE official ALTER birthday TYPE DATE');
        $this->addSql('COMMENT ON COLUMN official.birthday IS \'\'');
        $this->addSql('ALTER TABLE term ALTER id TYPE INT');
        $this->addSql('ALTER TABLE term ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE term ALTER official_id TYPE VARCHAR');
        $this->addSql('ALTER TABLE term ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE term ALTER end_date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN term.start_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN term.end_date IS \'\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE processed_messages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE processed_messages (id INT NOT NULL, run_id INT NOT NULL, attempt SMALLINT NOT NULL, message_type VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, dispatched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, memory_usage INT NOT NULL, transport VARCHAR(255) NOT NULL, tags VARCHAR(255) DEFAULT NULL, failure_type VARCHAR(255) DEFAULT NULL, failure_message TEXT DEFAULT NULL, results JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN processed_messages.dispatched_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN processed_messages.received_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN processed_messages.finished_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE official DROP ids');
        $this->addSql('ALTER TABLE official DROP marking');
        $this->addSql('ALTER TABLE official ALTER birthday TYPE DATE');
        $this->addSql('COMMENT ON COLUMN official.birthday IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE term ALTER id TYPE INT');
        $this->addSql('ALTER TABLE term ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE term ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE term ALTER end_date TYPE DATE');
        $this->addSql('ALTER TABLE term ALTER official_id TYPE VARCHAR(255)');
        $this->addSql('COMMENT ON COLUMN term.start_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN term.end_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
